<?php

namespace App\Services;

use App\Exceptions\LoginInvalidException;

class AuthService
{
    /**
     * The login function takes an email and password as input, attempts to authenticate the user, and
     * returns an access token if successful.
     * 
     * @param string email The email parameter is a string that represents the user's email address.
     * @param string password The password parameter is a string that represents the user's password.
     * 
     * @return array The login function returns an array with two keys: 'access_token' and
     * 'token_type'. The 'access_token' key contains the authentication token generated by the
     * auth()->attempt() method, and the 'token_type' key specifies the type of token, which is
     * 'Bearer' in this case.
     */
    public function login(string $email, string $password): array
    {
        $credentials = [
            'email' => $email,
            'password' => $password
        ];

        if (!$token = auth('api')->attempt($credentials)) {
            throw new LoginInvalidException();
        }

        return [
            'access_token' => $token,
            'token_type' => 'Bearer',
        ];
    }
}
